// === SEKTIONEN ===
// Die Modelle sind in 3 Hauptsektionen eingeteilt:
// 1. CHATBOTS & LLMs - Einfache Text-Modelle für Konversation und Reasoning
// 2. AI AGENTS - Autonome Agenten für Coding und komplexe Workflows
// 3. SPEZIAL-KI - Video, Audio, Bildgenerierung, Multimodal-Spezialisten

export type ModelSection = 'chatbot' | 'agent' | 'specialist';

export interface ModelData {
  id: string;
  name: string;
  provider: string;
  type: string;
  section: ModelSection; // Hauptsektion für die Gruppierung
  category: string[];
  description: string;
  context_window: number;
  pricing_input: number;
  pricing_output: number;
  api_available: boolean;
  release_date: string;
  benchmarks: {
    mmlu?: number;
    humaneval?: number;
    math?: number;
    gpqa?: number;
    aesthetics?: number;
    prompt_adherence?: number;
    quality?: number;
    coherence?: number;
    arena_elo?: number;
  };
  pros: string[];
  cons: string[];
  best_for: string[];
  video_url: string;
  is_new?: boolean;
  is_archived?: boolean;
}

// Archiv-Grenze: 26. Februar 2026 - 6 Monate = 26. August 2025
// Alle Modelle mit release_date < 2025-08-26 sind archiviert

export const modelsData: ModelData[] = [
  // ============================================
  // SEKTION 1: CHATBOTS & LLMs
  // Aktuelle Modelle (Stand: 26. Februar 2026)
  // ============================================

  // Claude Opus 4.6 (Anthropic - Feb 5, 2026) - AKTUELL
  {
    id: "claude-opus-4-6",
    name: "Claude Opus 4.6",
    provider: "Anthropic",
    type: "llm",
    section: "chatbot",
    category: ["llm", "coding", "reasoning", "agentic"],
    description: "Anthropics smartestes Modell. Führend bei agentic coding, computer use, tool use und enterprise AI. Jetzt mit 1M Token Kontextfenster (Beta).",
    context_window: 1000000,
    pricing_input: 5.00,
    pricing_output: 25.00,
    api_available: true,
    release_date: "2026-02-05",
    benchmarks: { mmlu: 91.0, humaneval: 94.0, math: 85.0, gpqa: 91.3, arena_elo: 1380 },
    pros: ["Industry-leading agentic coding", "Computer use capabilities", "Bestes Enterprise AI", "Tool use & search", "1M Token Kontext (Beta)"],
    cons: ["Sehr teuer", "Hohe Latenz bei komplexen Tasks"],
    best_for: ["Enterprise Coding", "Agentic Workflows", "Computer Automation", "Complex Reasoning"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_new: false,
  },
  // Claude Sonnet 4.6 (Anthropic - Feb 17, 2026) - NEU
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    provider: "Anthropic",
    type: "llm",
    section: "chatbot",
    category: ["llm", "coding", "reasoning", "agentic"],
    description: "Anthropics leistungsstärkstes Sonnet-Modell. Volles Upgrade bei Coding, Computer Use, Long-Context Reasoning und Agent Planning. 1M Token Kontextfenster (Beta).",
    context_window: 1000000,
    pricing_input: 3.00,
    pricing_output: 15.00,
    api_available: true,
    release_date: "2026-02-17",
    benchmarks: { mmlu: 90.2, humaneval: 93.5, math: 83.0, gpqa: 89.5, arena_elo: 1372 },
    pros: ["Opus-level Performance", "1M Token Kontext (Beta)", "Hervorragendes Computer Use", "Bessere Instruction Following", "Weniger Overengineering"],
    cons: ["Teurer als frühere Sonnet-Versionen", "Hohe Latenz bei komplexen Tasks"],
    best_for: ["Daily Coding", "Computer Automation", "Long Context Tasks", "Agentic Workflows"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_new: true,
  },
  // GPT-5.2 (OpenAI - Jan 2026) - AKTUELL
  {
    id: "gpt-5-2",
    name: "GPT-5.2",
    provider: "OpenAI",
    type: "llm",
    section: "chatbot",
    category: ["llm", "coding", "reasoning"],
    description: "OpenAIs neuestes Flaggschiff. Smarter und präziser als GPT-5. Führend bei Coding und agentic Tasks.",
    context_window: 256000,
    pricing_input: 5.00,
    pricing_output: 15.00,
    api_available: true,
    release_date: "2026-01-15",
    benchmarks: { mmlu: 90.5, humaneval: 93.5, math: 82.0, gpqa: 92.4, arena_elo: 1375 },
    pros: ["Höchste Präzision", "256K Kontext", "Bestes Coding", "Nativer Tool Support"],
    cons: ["Teuer", "Rate Limits bei hoher Nachfrage"],
    best_for: ["Complex Coding", "Long Context Tasks", "Agentic Workflows", "Research"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_new: true,
  },
  // GPT-5.1 (OpenAI - Nov 2025) - AKTUELL
  {
    id: "gpt-5-1",
    name: "GPT-5.1",
    provider: "OpenAI",
    type: "llm",
    section: "chatbot",
    category: ["llm", "coding", "reasoning"],
    description: "Verbesserte Version von GPT-5 mit konfigurierbarem Reasoning-Aufwand und besserer Persönlichkeit.",
    context_window: 128000,
    pricing_input: 1.25,
    pricing_output: 10.00,
    api_available: true,
    release_date: "2025-11-13",
    benchmarks: { mmlu: 89.8, humaneval: 92.5, math: 81.0, gpqa: 90.0, arena_elo: 1365 },
    pros: ["Konfigurierbares Reasoning", "Gute Preisgestaltung", "Zuverlässig", "Wärmerer Ton"],
    cons: ["Weniger leistungsfähig als 5.2", "Keine Echtzeit-Informationen"],
    best_for: ["Daily Coding", "General Tasks", "API Integration", "Prototyping"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_new: true,
  },
  // GPT-5 (OpenAI - Dec 2025) - AKTUELL
  {
    id: "gpt-5",
    name: "GPT-5",
    provider: "OpenAI",
    type: "llm",
    section: "chatbot",
    category: ["llm", "coding", "reasoning"],
    description: "OpenAIs Hauptmodell für Coding und agentic Tasks. Configurable reasoning effort.",
    context_window: 128000,
    pricing_input: 2.50,
    pricing_output: 10.00,
    api_available: true,
    release_date: "2025-12-10",
    benchmarks: { mmlu: 89.5, humaneval: 92.0, math: 80.0, gpqa: 68.0, arena_elo: 1360 },
    pros: ["Ausgewogenes Preis-Leistung", "Guter Kontext", "Zuverlässig", "Großes Ökosystem"],
    cons: ["Weniger leistungsfähig als 5.2", "Keine Echtzeit-Informationen"],
    best_for: ["Daily Coding", "General Tasks", "API Integration", "Prototyping"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_new: true,
  },
  // GPT-5 mini (OpenAI - Dec 2025) - AKTUELL
  {
    id: "gpt-5-mini",
    name: "GPT-5 Mini",
    provider: "OpenAI",
    type: "llm",
    section: "chatbot",
    category: ["llm", "fast", "budget"],
    description: "Schnellste, kosteneffizienteste Version von GPT-5. Für gut definierte Tasks.",
    context_window: 128000,
    pricing_input: 0.15,
    pricing_output: 0.60,
    api_available: true,
    release_date: "2025-12-10",
    benchmarks: { mmlu: 85.0, humaneval: 88.0, math: 75.0, gpqa: 58.0, arena_elo: 1320 },
    pros: ["Sehr günstig", "Schnell", "Gut für einfache Tasks", "128K Kontext"],
    cons: ["Weniger leistungsfähig", "Kein Reasoning"],
    best_for: ["Simple Tasks", "High Volume", "Prototyping", "Chatbots"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_new: true,
  },
  // Gemini 3.1 Pro (Google - Feb 2026) - AKTUELL
  {
    id: "gemini-3-1-pro",
    name: "Gemini 3.1 Pro",
    provider: "Google",
    type: "multimodal",
    section: "chatbot",
    category: ["llm", "multimodal", "reasoning", "coding"],
    description: "Googles neuestes Flaggschiff mit 77.1% auf ARC-AGI-2. Führend bei Reasoning und agentic Tasks.",
    context_window: 1000000,
    pricing_input: 2.00,
    pricing_output: 12.00,
    api_available: true,
    release_date: "2026-02-19",
    benchmarks: { mmlu: 91.8, humaneval: 92.0, math: 80.0, gpqa: 94.3, arena_elo: 1370 },
    pros: ["77.1% ARC-AGI-2", "1M Token Kontext", "Sehr günstig", "Starke Agentic-Capabilities"],
    cons: ["Noch Preview", "Höhere Latenz bei komplexen Tasks"],
    best_for: ["Complex Reasoning", "Agentic Workflows", "Long Context", "Research"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_new: true,
  },
  // Gemini 3 Flash (Google - Feb 2026) - AKTUELL
  {
    id: "gemini-3-flash",
    name: "Gemini 3 Flash",
    provider: "Google",
    type: "multimodal",
    section: "chatbot",
    category: ["llm", "multimodal", "fast", "budget"],
    description: "Schnelles multimodales Modell mit 1M Token Kontext und adaptivem Thinking.",
    context_window: 1000000,
    pricing_input: 0.50,
    pricing_output: 3.00,
    api_available: true,
    release_date: "2026-02-05",
    benchmarks: { mmlu: 88.0, humaneval: 89.0, math: 75.0, gpqa: 90.0, arena_elo: 1330 },
    pros: ["1M Token Kontext", "Sehr günstig", "Schnell", "Multimodal"],
    cons: ["Weniger leistungsfähig als Pro", "Thinking manchmal inkonsistent"],
    best_for: ["Lange Dokumente", "Agent-Apps", "Kostenbewusste Projekte", "Echtzeit"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_new: true,
  },
  // Grok 3 (xAI - Feb 2025) - ARCHIV (>6 Monate alt)
  {
    id: "grok-3",
    name: "Grok 3",
    provider: "xAI",
    type: "llm",
    section: "chatbot",
    category: ["llm", "real-time", "archiv"],
    description: "[ARCHIV - Feb 2025] xAIs Modell mit Echtzeit-X-Integration und Reasoning-Fähigkeiten.",
    context_window: 128000,
    pricing_input: 3.00,
    pricing_output: 15.00,
    api_available: true,
    release_date: "2025-02-17",
    benchmarks: { mmlu: 86.5, humaneval: 89.0, math: 78.0, gpqa: 58.0, arena_elo: 1310 },
    pros: ["Echtzeit-X-Integration", "Weniger zensiert", "Reasoning-Modus"],
    cons: ["Veraltet", "Nur über X/Twitter", "Weniger reif"],
    best_for: ["Historische Vergleiche"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_archived: true,
  },
  // DeepSeek R1 (Reasoning) - ARCHIV (>6 Monate alt)
  {
    id: "deepseek-r1",
    name: "DeepSeek R1",
    provider: "DeepSeek",
    type: "llm",
    section: "chatbot",
    category: ["llm", "reasoning", "open-source", "archiv"],
    description: "[ARCHIV - Jan 2025] Reasoning-Modell mit Chain-of-Thought. Konkurrenzfähig mit o1.",
    context_window: 128000,
    pricing_input: 0.55,
    pricing_output: 2.19,
    api_available: true,
    release_date: "2025-01-20",
    benchmarks: { mmlu: 87.5, humaneval: 91.5, math: 91.2, gpqa: 65.0, arena_elo: 1295 },
    pros: ["Hervorragendes Reasoning", "Sichtbares Chain-of-Thought", "Sehr günstig"],
    cons: ["Veraltet", "Nur Englisch/Chinesisch", "Zensur"],
    best_for: ["Historische Vergleiche"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_archived: true,
  },
  // DeepSeek V3 - ARCHIV (>6 Monate alt)
  {
    id: "deepseek-v3",
    name: "DeepSeek V3",
    provider: "DeepSeek",
    type: "llm",
    section: "chatbot",
    category: ["llm", "coding", "open-source", "archiv"],
    description: "[ARCHIV - Dec 2024] Open-Source-Modell mit extrem günstigen Preisen.",
    context_window: 128000,
    pricing_input: 0.28,
    pricing_output: 0.42,
    api_available: true,
    release_date: "2024-12-26",
    benchmarks: { mmlu: 85.2, humaneval: 89.8, math: 74.0, gpqa: 55.0, arena_elo: 1278 },
    pros: ["Extrem günstig", "Open Source", "Hervorragendes Reasoning"],
    cons: ["Veraltet", "Zensur bei sensiblen Themen"],
    best_for: ["Historische Vergleiche"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_archived: true,
  },
  // Qwen 2.5 Max (Alibaba) - ARCHIV (>6 Monate alt)
  {
    id: "qwen-2-5-max",
    name: "Qwen 2.5 Max",
    provider: "Alibaba",
    type: "llm",
    section: "chatbot",
    category: ["llm", "coding", "open-source", "archiv"],
    description: "[ARCHIV - Jan 2025] Alibabas stärkstes Modell. Top 10 auf LMSYS Arena.",
    context_window: 128000,
    pricing_input: 1.60,
    pricing_output: 6.40,
    api_available: true,
    release_date: "2025-01-28",
    benchmarks: { mmlu: 86.0, humaneval: 88.5, math: 73.0, gpqa: 54.0, arena_elo: 1332 },
    pros: ["Top-Performance", "Gute Chinesisch-Übersetzung"],
    cons: ["Veraltet", "Weniger bekannt außerhalb Chinas"],
    best_for: ["Historische Vergleiche"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_archived: true,
  },
  // Llama 3.3 70B - ARCHIV (>6 Monate alt)
  {
    id: "llama-3-3-70b",
    name: "Llama 3.3 70B",
    provider: "Meta",
    type: "llm",
    section: "chatbot",
    category: ["llm", "open-source", "archiv"],
    description: "[ARCHIV - Dec 2024] Effizientes Open-Source-Modell. Fast gleiche Performance wie 405B.",
    context_window: 128000,
    pricing_input: 0.12,
    pricing_output: 0.30,
    api_available: true,
    release_date: "2024-12-06",
    benchmarks: { mmlu: 82.1, humaneval: 86.5, math: 70.0, gpqa: 48.0, arena_elo: 1250 },
    pros: ["Kostenlos", "Open Source", "Effizient"],
    cons: ["Veraltet", "Weniger leistungsfähig"],
    best_for: ["Historische Vergleiche"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_archived: true,
  },
  // GPT-4o Mini - ARCHIV (>6 Monate alt)
  {
    id: "gpt-4o-mini",
    name: "GPT-4o Mini",
    provider: "OpenAI",
    type: "llm",
    section: "chatbot",
    category: ["llm", "budget", "archiv"],
    description: "[ARCHIV - Jul 2024] Günstige Alternative zu GPT-4o.",
    context_window: 128000,
    pricing_input: 0.15,
    pricing_output: 0.60,
    api_available: true,
    release_date: "2024-07-18",
    benchmarks: { mmlu: 78.9, humaneval: 81.2, math: 68.0, gpqa: 42.0, arena_elo: 1220 },
    pros: ["Sehr günstig", "Schnell"],
    cons: ["Veraltet", "Weniger leistungsfähig"],
    best_for: ["Historische Vergleiche"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_archived: true,
  },
  // Mistral Large 2 - ARCHIV (>6 Monate alt)
  {
    id: "mistral-large-2",
    name: "Mistral Large 2",
    provider: "Mistral AI",
    type: "llm",
    section: "chatbot",
    category: ["llm", "european", "archiv"],
    description: "[ARCHIV - Jul 2024] Europäisches Modell mit starken Multilingual-Fähigkeiten.",
    context_window: 128000,
    pricing_input: 2.00,
    pricing_output: 6.00,
    api_available: true,
    release_date: "2024-07-24",
    benchmarks: { mmlu: 81.8, humaneval: 85.2, math: 68.0, gpqa: 48.0, arena_elo: 1245 },
    pros: ["Europäisch", "Multilingual"],
    cons: ["Veraltet", "Kleinere Community"],
    best_for: ["Historische Vergleiche"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_archived: true,
  },

  // ============================================
  // ARCHIV: Modelle älter als 6 Monate (vor Aug 2025)
  // ============================================

  // Claude 3.7 Sonnet (Feb 2025) - ARCHIV (>6 Monate alt)
  {
    id: "claude-3-7-sonnet",
    name: "Claude 3.7 Sonnet",
    provider: "Anthropic",
    type: "llm",
    section: "chatbot",
    category: ["llm", "coding", "reasoning", "archiv"],
    description: "[ARCHIV - Feb 2025] Von Claude Opus 4.6 abgelöst. War das erste Hybrid-Reasoning-Modell.",
    context_window: 200000,
    pricing_input: 3.00,
    pricing_output: 15.00,
    api_available: true,
    release_date: "2025-02-24",
    benchmarks: { mmlu: 88.5, humaneval: 92.5, math: 76.0, gpqa: 62.0, arena_elo: 1335 },
    pros: ["Hybrid-Reasoning", "Gutes Coding", "Großer Kontext"],
    cons: ["Veraltet", "Von Opus 4.6 überholt"],
    best_for: ["Historische Vergleiche"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_archived: true,
  },
  // GPT-4.5 (OpenAI - Feb 27, 2025) - ARCHIV (>6 Monate alt)
  {
    id: "gpt-4-5",
    name: "GPT-4.5",
    provider: "OpenAI",
    type: "llm",
    section: "chatbot",
    category: ["llm", "reasoning", "archiv"],
    description: "[ARCHIV - Feb 2025] Von GPT-5 und GPT-5.2 abgelöst. War OpenAIs größtes Chat-Modell.",
    context_window: 128000,
    pricing_input: 75.00,
    pricing_output: 150.00,
    api_available: true,
    release_date: "2025-02-27",
    benchmarks: { mmlu: 89.0, humaneval: 91.5, math: 78.0, gpqa: 62.0, arena_elo: 1340 },
    pros: ["Hohe EQ", "Weniger Halluzinationen"],
    cons: ["Veraltet", "Von GPT-5 überholt", "Teuer"],
    best_for: ["Historische Vergleiche"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_archived: true,
  },

  // ============================================
  // SEKTION 2: AI AGENTS
  // Autonome Agenten für Coding, Planung, Workflows
  // ============================================

  // GPT-5.3-Codex (OpenAI - Feb 2026) - AKTUELL
  {
    id: "gpt-5-3-codex",
    name: "GPT-5.3-Codex",
    provider: "OpenAI",
    type: "agent",
    section: "agent",
    category: ["agent", "coding", "autonomous"],
    description: "Der fähigste agentische Coding-Modell bis heute. 25% schneller als GPT-5.2-Codex. State-of-the-art auf SWE-Bench Pro und Terminal-Bench 2.0.",
    context_window: 256000,
    pricing_input: 1.75,
    pricing_output: 14.00,
    api_available: true,
    release_date: "2026-02-05",
    benchmarks: { humaneval: 95.0, mmlu: 90.0, gpqa: 90.0 },
    pros: ["Bestes agentisches Coding", "77.3% Terminal-Bench 2.0", "56.8% SWE-Bench Pro", "Echtzeit-Interaktion"],
    cons: ["Noch kein API-Zugang (nur ChatGPT)", "Hoher Token-Verbrauch"],
    best_for: ["Autonomes Coding", "Long-horizon Tasks", "Software Engineering", "Debugging"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_new: true,
  },
  // Devin - Cognition AI - ARCHIV (>6 Monate alt)
  {
    id: "devin",
    name: "Devin",
    provider: "Cognition AI",
    type: "agent",
    section: "agent",
    category: ["agent", "coding", "autonomous", "archiv"],
    description: "[ARCHIV - Mar 2024] Autonomer Software-Engineering-Agent. Von GPT-5.3-Codex und Claude Opus 4.6 überholt.",
    context_window: 128000,
    pricing_input: 0,
    pricing_output: 0,
    api_available: false,
    release_date: "2024-03-12",
    benchmarks: { humaneval: 95.0 },
    pros: ["Vollautonom", "End-to-End-Workflow"],
    cons: ["Veraltet", "Sehr teuer ($500+/Monat)", "Warteliste"],
    best_for: ["Historische Vergleiche"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_archived: true,
  },
  // Claude Code - ARCHIV (>6 Monate alt)
  {
    id: "claude-code",
    name: "Claude Code",
    provider: "Anthropic",
    type: "agent",
    section: "agent",
    category: ["agent", "coding", "terminal", "archiv"],
    description: "[ARCHIV - Feb 2025] Kommandozeilen-Tool für agentisches Coding. Von Claude Opus 4.6 überholt.",
    context_window: 200000,
    pricing_input: 3.00,
    pricing_output: 15.00,
    api_available: true,
    release_date: "2025-02-24",
    benchmarks: { humaneval: 92.5 },
    pros: ["Kostenlos (für Preview)", "Integriert mit Claude 3.7"],
    cons: ["Veraltet", "Nur Preview", "Terminal-only"],
    best_for: ["Historische Vergleiche"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_archived: true,
  },
  // GitHub Copilot - AKTUELL (kontinuierlich aktualisiert)
  {
    id: "github-copilot-agent",
    name: "GitHub Copilot",
    provider: "GitHub/OpenAI",
    type: "agent",
    section: "agent",
    category: ["agent", "coding", "ide"],
    description: "Der bekannteste Coding-Assistent mit Workspace-Agent. Integriert in VS Code, JetBrains, Neovim. Jetzt mit Gemini 3.1 Pro Unterstützung.",
    context_window: 128000,
    pricing_input: 0,
    pricing_output: 0,
    api_available: false,
    release_date: "2025-06-01",
    benchmarks: { humaneval: 90.0 },
    pros: ["Sehr verbreitet", "Gute IDE-Integration", "Zuverlässig", "Große Community"],
    cons: ["Weniger agentisch als Cursor", "Code bleibt in der Cloud"],
    best_for: ["Tägliches Coding", "Einsteiger", "Alle IDEs", "GitHub-User"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_new: false,
  },

  // ============================================
  // SEKTION 3: SPEZIAL-KI
  // Video, Audio, Bildgenerierung, Multimodal-Spezialisten
  // ============================================

  // Gemini 2.5 Pro (Juni 2025) - ARCHIV (>6 Monate alt)
  {
    id: "gemini-2-5-pro",
    name: "Gemini 2.5 Pro",
    provider: "Google",
    type: "multimodal",
    section: "specialist",
    category: ["multimodal", "vision", "long-context", "archiv"],
    description: "[ARCHIV - Jun 2025] Von Gemini 3 Pro abgelöst. War Googles leistungsstärkstes Modell mit 1M Token Kontextfenster.",
    context_window: 1000000,
    pricing_input: 1.25,
    pricing_output: 10.00,
    api_available: true,
    release_date: "2025-06-01",
    benchmarks: { mmlu: 89.5, humaneval: 92.0, math: 80.0, gpqa: 65.0, arena_elo: 1350 },
    pros: ["1M Token Kontextfenster", "State-of-the-art Coding", "Native Multimodalität"],
    cons: ["Von Gemini 3 Pro abgelöst", "Höhere Latenz als Flash"],
    best_for: ["Historische Vergleiche"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_archived: true,
  },
  // Gemini 2.5 Flash (Juni 2025) - ARCHIV (>6 Monate alt)
  {
    id: "gemini-2-5-flash",
    name: "Gemini 2.5 Flash",
    provider: "Google",
    type: "multimodal",
    section: "specialist",
    category: ["multimodal", "vision", "fast", "archiv"],
    description: "[ARCHIV - Jun 2025] Von Gemini 3 Flash abgelöst. War schnelles multimodales Modell mit adaptivem Thinking.",
    context_window: 1000000,
    pricing_input: 0.15,
    pricing_output: 0.60,
    api_available: true,
    release_date: "2025-06-01",
    benchmarks: { mmlu: 86.5, humaneval: 89.0, math: 75.0, gpqa: 58.0, arena_elo: 1310 },
    pros: ["1M Token Kontextfenster", "Sehr günstig", "Adaptive Thinking-Budget"],
    cons: ["Von Gemini 3 Flash abgelöst", "Thinking manchmal inkonsistent"],
    best_for: ["Historische Vergleiche"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_archived: true,
  },
  // Gemini 2.5 Flash-Lite (Juli 2025) - ARCHIV (>6 Monate alt)
  {
    id: "gemini-2-5-flash-lite",
    name: "Gemini 2.5 Flash-Lite",
    provider: "Google",
    type: "multimodal",
    section: "specialist",
    category: ["multimodal", "vision", "fast", "budget", "archiv"],
    description: "[ARCHIV - Jul 2025] Von Gemini 3 Flash abgelöst. War kostengünstigste Variante der Gemini 2.5 Familie.",
    context_window: 1000000,
    pricing_input: 0.075,
    pricing_output: 0.30,
    api_available: true,
    release_date: "2025-07-01",
    benchmarks: { mmlu: 84.0, humaneval: 86.0, math: 70.0, gpqa: 52.0, arena_elo: 1280 },
    pros: ["Sehr günstig", "1M Kontext", "Schnell"],
    cons: ["Von Gemini 3 Flash abgelöst", "Kein Thinking-Modus"],
    best_for: ["Historische Vergleiche"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_archived: true,
  },
  // ARCHIV: Gemini 2.0 Pro (veraltet durch 2.5)
  {
    id: "gemini-2-0-pro",
    name: "Gemini 2.0 Pro",
    provider: "Google",
    type: "multimodal",
    section: "specialist",
    category: ["multimodal", "vision", "long-context", "archiv"],
    description: "[ARCHIV] Von Gemini 2.5 Pro abgelöst. War Googles leistungsstärkstes Modell mit 2M Token.",
    context_window: 2000000,
    pricing_input: 1.25,
    pricing_output: 10.00,
    api_available: true,
    release_date: "2025-02-05",
    benchmarks: { mmlu: 87.8, humaneval: 90.2, math: 75.0, gpqa: 58.0, arena_elo: 1320 },
    pros: ["Größtes Kontextfenster (2M)", "Hervorragendes Reasoning", "Multimodal"],
    cons: ["Von 2.5 Pro abgelöst", "Höhere Latenz"],
    best_for: ["Historische Vergleiche"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_archived: true,
  },
  // ARCHIV: Gemini 2.0 Flash (veraltet durch 2.5)
  {
    id: "gemini-2-0-flash",
    name: "Gemini 2.0 Flash",
    provider: "Google",
    type: "multimodal",
    section: "specialist",
    category: ["multimodal", "vision", "fast", "archiv"],
    description: "[ARCHIV] Von Gemini 2.5 Flash abgelöst. War schnelles multimodales Modell mit 1M Kontext.",
    context_window: 1000000,
    pricing_input: 0.10,
    pricing_output: 0.40,
    api_available: true,
    release_date: "2025-02-05",
    benchmarks: { mmlu: 84.5, humaneval: 87.0, math: 72.0, gpqa: 52.0, arena_elo: 1280 },
    pros: ["Riesiges 1M Kontextfenster", "Sehr günstig", "Multimodal"],
    cons: ["Von 2.5 Flash abgelöst", "Kein Thinking"],
    best_for: ["Historische Vergleiche"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_archived: true,
  },
  // GPT-4o (Multimodal) - ARCHIV (>6 Monate alt)
  {
    id: "gpt-4o",
    name: "GPT-4o",
    provider: "OpenAI",
    type: "multimodal",
    section: "specialist",
    category: ["multimodal", "vision", "audio", "archiv"],
    description: "[ARCHIV - May 2024] OpenAIs multimodales Flaggschiff. Von GPT-5-Familie abgelöst.",
    context_window: 128000,
    pricing_input: 2.50,
    pricing_output: 10.00,
    api_available: true,
    release_date: "2024-05-13",
    benchmarks: { mmlu: 87.2, humaneval: 90.1, math: 76.6, gpqa: 53.6, arena_elo: 1312 },
    pros: ["Multimodal", "Großes Ökosystem", "Zuverlässige API"],
    cons: ["Veraltet", "Von GPT-5 überholt"],
    best_for: ["Historische Vergleiche"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_archived: true,
  },

  // === ARCHIV SECTION ===
  // Veraltete Modelle nur für historische Vergleiche
  
  // ARCHIV: Claude 3.5 Sonnet (veraltet durch 3.7)
  {
    id: "claude-3-5-sonnet",
    name: "Claude 3.5 Sonnet",
    provider: "Anthropic",
    type: "llm",
    section: "chatbot",
    category: ["llm", "coding", "reasoning", "archiv"],
    description: "[ARCHIV] Ausgezeichnetes Preis-Leistungs-Verhältnis. Von Claude 3.7 Sonnet abgelöst.",
    context_window: 200000,
    pricing_input: 3.00,
    pricing_output: 15.00,
    api_available: true,
    release_date: "2024-06-20",
    benchmarks: { mmlu: 85.4, humaneval: 92.0, math: 71.1, gpqa: 59.4, arena_elo: 1301 },
    pros: ["Exzellentes Coding", "Großes Kontextfenster", "Natürliche Konversation"],
    cons: ["Von 3.7 abgelöst", "Kein Reasoning-Modus"],
    best_for: ["Historische Vergleiche"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_archived: true,
  },
  // ARCHIV: Midjourney v6
  {
    id: "midjourney-v6",
    name: "Midjourney v6",
    provider: "Midjourney",
    type: "image",
    section: "specialist",
    category: ["image", "art", "archiv"],
    description: "[ARCHIV] Führendes KI-Bildgenerierungsmodell für künstlerische Bilder.",
    context_window: 0,
    pricing_input: 8.00,
    pricing_output: 0,
    api_available: false,
    release_date: "2023-12-21",
    benchmarks: { aesthetics: 95, prompt_adherence: 92 },
    pros: ["Beste Bildqualität", "Künstlerischer Stil", "Aktive Community"],
    cons: ["Keine API", "Discord erforderlich", "Teuer"],
    best_for: ["Historische Vergleiche"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_archived: true,
  },
  // ARCHIV: DALL-E 3
  {
    id: "dall-e-3",
    name: "DALL-E 3",
    provider: "OpenAI",
    type: "image",
    section: "specialist",
    category: ["image", "api", "archiv"],
    description: "[ARCHIV] OpenAIs Bildgenerierungsmodell mit exzellenter Prompt-Einhaltung.",
    context_window: 0,
    pricing_input: 4.00,
    pricing_output: 0,
    api_available: true,
    release_date: "2023-10-01",
    benchmarks: { aesthetics: 85, prompt_adherence: 95 },
    pros: ["API verfügbar", "Gute Prompt-Einhaltung", "ChatGPT-Integration"],
    cons: ["Weniger künstlerisch", "Eingeschränkte Kontrolle"],
    best_for: ["Historische Vergleiche"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_archived: true,
  },
  // ARCHIV: Sora
  {
    id: "sora",
    name: "Sora",
    provider: "OpenAI",
    type: "video",
    section: "specialist",
    category: ["video", "multimodal", "archiv"],
    description: "[ARCHIV] KI-Modell für die Generierung realistischer Videos aus Text.",
    context_window: 0,
    pricing_input: 0,
    pricing_output: 0,
    api_available: false,
    release_date: "2024-12-09",
    benchmarks: { quality: 90, coherence: 88 },
    pros: ["Realistische Videos", "Lange Sequenzen", "Physik-Verständnis"],
    cons: ["Nur für ausgewählte User", "Hohe Kosten"],
    best_for: ["Historische Vergleiche"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_archived: true,
  },
];

// Top 5 Modelle für März 2026
// Quelle: LMSYS Arena Leaderboard (lmarena.ai) - Stand: 2. Mär 2026
// Sortiert nach: Arena Elo (höchster zuerst)
export const topModels = [
  {
    rank: 1,
    name: "Claude Opus 4.6",
    provider: "Anthropic",
    arena_elo: 1505,
    mmlu: 91.0,
    context: "1M",
    price_input: 5.00,
    price_output: 25.00,
    highlight: "#1 LMSYS Arena - Agentic Planning & Research Leader",
    release_date: "2026-02-05",
  },
  {
    rank: 2,
    name: "Claude Opus 4.6 Thinking",
    provider: "Anthropic",
    arena_elo: 1504,
    mmlu: 91.0,
    context: "1M",
    price_input: 5.00,
    price_output: 25.00,
    highlight: "#2 LMSYS Arena - Self-Correction Logic & Reasoning",
    release_date: "2026-02-05",
  },
  {
    rank: 3,
    name: "Gemini 3.1 Pro",
    provider: "Google",
    arena_elo: 1500,
    mmlu: 91.8,
    context: "1M",
    price_input: 2.00,
    price_output: 12.00,
    highlight: "#3 LMSYS Arena - 77.1% ARC-AGI-2, PhD-level Science (HLE 44.4%)",
    release_date: "2026-02-19",
  },
  {
    rank: 4,
    name: "Gemini 3 Pro",
    provider: "Google",
    arena_elo: 1486,
    mmlu: 91.5,
    context: "1M",
    price_input: 2.50,
    price_output: 10.00,
    highlight: "#4 LMSYS Arena - Starke Multimodalität",
    release_date: "2026-01-20",
  },
  {
    rank: 5,
    name: "Seed 2.0 Pro",
    provider: "ByteDance",
    arena_elo: 1475,
    mmlu: 87.0,
    context: "256K",
    price_input: 0.47,
    price_output: 2.37,
    highlight: "#5 LMSYS Arena - Real-time Video Synthesis, 10x günstiger",
    release_date: "2026-02-14",
  },
];

// Neue Modelle (letzte 30 Tage)
export const newThisWeek = [
  {
    name: "Claude Sonnet 4.6",
    provider: "Anthropic",
    release_date: "2026-02-17",
    description: "Anthropics leistungsstärkstes Sonnet-Modell mit Opus-level Performance und 1M Token Kontext",
    category: "LLM / Agentic",
  },
  {
    name: "Gemini 3.1 Pro",
    provider: "Google",
    release_date: "2026-02-19",
    description: "Googles neuestes Flaggschiff mit 77.1% auf ARC-AGI-2 - Durchbruch bei Reasoning",
    category: "LLM / Multimodal",
  },
  {
    name: "Gemini 3 Flash",
    provider: "Google",
    release_date: "2026-02-05",
    description: "Schnelles multimodales Modell mit 1M Token Kontext und adaptivem Thinking",
    category: "LLM / Multimodal",
  },
  {
    name: "GPT-5.3-Codex",
    provider: "OpenAI",
    release_date: "2026-02-05",
    description: "Der fähigste agentische Coding-Modell - 77.3% auf Terminal-Bench 2.0",
    category: "AI Agent / Coding",
  },
  {
    name: "Claude Opus 4.6",
    provider: "Anthropic",
    release_date: "2026-02-05",
    description: "Anthropics smartestes Modell mit 1M Token Kontext (Beta)",
    category: "LLM / Agentic",
  },
];

// Preisvergleich - Aktuelle Modelle (Stand: Feb 2026)
export const priceComparison = [
  { model: "GPT-5 Mini", provider: "OpenAI", input: 0.15, output: 0.60, context: "128K", release: "2025-12" },
  { model: "Gemini 3 Flash", provider: "Google", input: 0.50, output: 3.00, context: "1M", release: "2026-02" },
  { model: "GPT-5.1", provider: "OpenAI", input: 1.25, output: 10.00, context: "128K", release: "2025-11" },
  { model: "GPT-5.3-Codex", provider: "OpenAI", input: 1.75, output: 14.00, context: "256K", release: "2026-02" },
  { model: "Gemini 3.1 Pro", provider: "Google", input: 2.00, output: 12.00, context: "1M", release: "2026-02" },
  { model: "GPT-5", provider: "OpenAI", input: 2.50, output: 10.00, context: "128K", release: "2025-12" },
  { model: "Claude Sonnet 4.6", provider: "Anthropic", input: 3.00, output: 15.00, context: "1M", release: "2026-02" },
  { model: "GPT-5.2", provider: "OpenAI", input: 5.00, output: 15.00, context: "256K", release: "2026-01" },
  { model: "Claude Opus 4.6", provider: "Anthropic", input: 5.00, output: 25.00, context: "1M", release: "2026-02" },
];
