export interface ModelData {
  id: string;
  name: string;
  provider: string;
  type: string;
  category: string[];
  description: string;
  context_window: number;
  pricing_input: number;
  pricing_output: number;
  api_available: boolean;
  release_date: string;
  benchmarks: {
    mmlu?: number;
    humaneval?: number;
    math?: number;
    gpqa?: number;
    aesthetics?: number;
    prompt_adherence?: number;
    quality?: number;
    coherence?: number;
  };
  pros: string[];
  cons: string[];
  best_for: string[];
  video_url: string;
}

export const modelsData: ModelData[] = [
  {
    id: "gpt-4-turbo",
    name: "GPT-4 Turbo",
    provider: "OpenAI",
    type: "llm",
    category: ["llm", "coding", "reasoning"],
    description: "Leistungsstarkes LLM mit 128k Kontextfenster. Hervorragend für Coding und komplexe Aufgaben.",
    context_window: 128000,
    pricing_input: 0.01,
    pricing_output: 0.03,
    api_available: true,
    release_date: "2023-11-06",
    benchmarks: { mmlu: 86.4, humaneval: 87.2, math: 72.9, gpqa: 48.0 },
    pros: ["Hervorragende Code-Generierung", "Großes Ökosystem", "Zuverlässige API"],
    cons: ["Höherer Preis", "Manchmal übermäßig vorsichtig"],
    best_for: ["Coding", "API-Integration", "Komplexe Aufgaben"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
  },
  {
    id: "claude-3-5-sonnet",
    name: "Claude 3.5 Sonnet",
    provider: "Anthropic",
    type: "llm",
    category: ["llm", "reasoning", "writing"],
    description: "Hervorragendes Reasoning und Coding. 200k Kontextfenster für lange Dokumente.",
    context_window: 200000,
    pricing_input: 0.003,
    pricing_output: 0.015,
    api_available: true,
    release_date: "2024-06-20",
    benchmarks: { mmlu: 88.7, humaneval: 92.0, math: 71.1, gpqa: 59.4 },
    pros: ["Exzellentes Reasoning", "Großes Kontextfenster", "Natürliche Konversation"],
    cons: ["Kein Internet-Zugriff", "Manchmal langsam"],
    best_for: ["Recherche", "Dokumentenanalyse", "Schreiben"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
  },
  {
    id: "gemini-pro-1-5",
    name: "Gemini Pro 1.5",
    provider: "Google",
    type: "llm",
    category: ["llm", "multimodal", "vision"],
    description: "Bis zu 1 Million Token Kontextfenster. Stark in Multimodal-Aufgaben.",
    context_window: 1000000,
    pricing_input: 0.0035,
    pricing_output: 0.0105,
    api_available: true,
    release_date: "2024-02-15",
    benchmarks: { mmlu: 85.9, humaneval: 84.1, math: 67.7, gpqa: 46.0 },
    pros: ["Riesiges Kontextfenster", "Google-Integration", "Multimodal"],
    cons: ["Inkonsistente Ergebnisse", "Weniger beliebt"],
    best_for: ["Lange Dokumente", "Video-Analyse", "Google-Ökosystem"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
  },
  {
    id: "llama-3-1-405b",
    name: "Llama 3.1 405B",
    provider: "Meta",
    type: "llm",
    category: ["llm", "open-source"],
    description: "Open Source LLM mit 405B Parametern. Kostenlos nutzbar für kommerzielle Zwecke.",
    context_window: 128000,
    pricing_input: 0,
    pricing_output: 0,
    api_available: true,
    release_date: "2024-07-23",
    benchmarks: { mmlu: 85.2, humaneval: 89.0, math: 73.0, gpqa: 50.0 },
    pros: ["Kostenlos", "Open Source", "Hohe Privatsphäre"],
    cons: ["Hohe Hardware-Anforderungen", "Komplexe Einrichtung"],
    best_for: ["Selbst-Hosting", "Datenschutz", "Forschung"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
  },
  {
    id: "kimi-k2-5",
    name: "Kimi K2.5",
    provider: "Moonshot AI",
    type: "llm",
    category: ["llm", "coding", "reasoning"],
    description: "Starke Performance in Coding und Reasoning. 256k Kontextfenster.",
    context_window: 256000,
    pricing_input: 0.002,
    pricing_output: 0.008,
    api_available: true,
    release_date: "2025-01-20",
    benchmarks: { mmlu: 87.2, humaneval: 90.5, math: 75.2, gpqa: 55.0 },
    pros: ["Sehr günstig", "Langer Kontext", "Starke Performance"],
    cons: ["Weniger bekannt", "Begrenzte Dokumentation"],
    best_for: ["Coding", "Budget-Projekte", "Asiatische Sprachen"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
  },
  {
    id: "gpt-4o",
    name: "GPT-4o",
    provider: "OpenAI",
    type: "multimodal",
    category: ["llm", "multimodal", "vision", "audio"],
    description: "OpenAIs schnellstes multimodales Modell. Text, Bild und Audio in Echtzeit.",
    context_window: 128000,
    pricing_input: 0.005,
    pricing_output: 0.015,
    api_available: true,
    release_date: "2024-05-13",
    benchmarks: { mmlu: 88.7, humaneval: 90.2, math: 76.6, gpqa: 53.6 },
    pros: ["Schnell", "Multimodal", "Gute Preis-Leistung"],
    cons: ["Weniger leistungsfähig als Turbo", "Begrenzte Vision"],
    best_for: ["Echtzeit-Anwendungen", "Bildanalyse", "Sprachassistenten"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
  },
  {
    id: "claude-3-opus",
    name: "Claude 3 Opus",
    provider: "Anthropic",
    type: "llm",
    category: ["llm", "reasoning", "writing"],
    description: "Anthropics leistungsstärkstes Modell für komplexe Aufgaben.",
    context_window: 200000,
    pricing_input: 0.015,
    pricing_output: 0.075,
    api_available: true,
    release_date: "2024-03-04",
    benchmarks: { mmlu: 86.8, humaneval: 84.9, math: 60.1, gpqa: 50.4 },
    pros: ["Höchste Qualität", "Tiefe Analyse", "Kreativität"],
    cons: ["Sehr teuer", "Langsamer"],
    best_for: ["Premium-Projekte", "Kreative Arbeit", "Forschung"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
  },
  {
    id: "midjourney-v6",
    name: "Midjourney v6",
    provider: "Midjourney",
    type: "image",
    category: ["image", "art"],
    description: "Führendes KI-Bildgenerierungsmodell für künstlerische Bilder.",
    context_window: 0,
    pricing_input: 0.08,
    pricing_output: 0,
    api_available: false,
    release_date: "2023-12-21",
    benchmarks: { aesthetics: 95, prompt_adherence: 92 },
    pros: ["Beste Bildqualität", "Künstlerischer Stil", "Aktive Community"],
    cons: ["Keine API", "Discord erforderlich", "Teuer"],
    best_for: ["Kunst", "Marketing", "Konzept-Design"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
  },
  {
    id: "dall-e-3",
    name: "DALL-E 3",
    provider: "OpenAI",
    type: "image",
    category: ["image", "api"],
    description: "OpenAIs Bildgenerierungsmodell mit exzellenter Prompt-Einhaltung.",
    context_window: 0,
    pricing_input: 0.04,
    pricing_output: 0,
    api_available: true,
    release_date: "2023-10-01",
    benchmarks: { aesthetics: 85, prompt_adherence: 95 },
    pros: ["API verfügbar", "Gute Prompt-Einhaltung", "ChatGPT-Integration"],
    cons: ["Weniger künstlerisch", "Eingeschränkte Kontrolle"],
    best_for: ["API-Integration", "Content-Erstellung", "ChatGPT-User"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
  },
  {
    id: "sora",
    name: "Sora",
    provider: "OpenAI",
    type: "video",
    category: ["video", "multimodal"],
    description: "KI-Modell für die Generierung realistischer Videos aus Text.",
    context_window: 0,
    pricing_input: 0,
    pricing_output: 0,
    api_available: false,
    release_date: "2024-02-15",
    benchmarks: { quality: 90, coherence: 88 },
    pros: ["Realistische Videos", "Lange Sequenzen", "Physik-Verständnis"],
    cons: ["Noch nicht öffentlich", "Hohe Kosten erwartet"],
    best_for: ["Video-Produktion", "Storyboarding", "Marketing"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
  },
];
