export interface ModelData {
  id: string;
  name: string;
  provider: string;
  type: string;
  category: string[];
  description: string;
  context_window: number;
  pricing_input: number;
  pricing_output: number;
  api_available: boolean;
  release_date: string;
  benchmarks: {
    mmlu?: number;
    humaneval?: number;
    math?: number;
    gpqa?: number;
    aesthetics?: number;
    prompt_adherence?: number;
    quality?: number;
    coherence?: number;
    arena_elo?: number;
  };
  pros: string[];
  cons: string[];
  best_for: string[];
  video_url: string;
  is_new?: boolean;
}

export const modelsData: ModelData[] = [
  // NEU: Claude 3.7 Sonnet (Feb 2025)
  {
    id: "claude-3-7-sonnet",
    name: "Claude 3.7 Sonnet",
    provider: "Anthropic",
    type: "llm",
    category: ["llm", "coding", "reasoning", "agent"],
    description: "Erstes Hybrid-Reasoning-Modell am Markt. Kann zwischen schnellen und erweiterten Denkprozessen wechseln. State-of-the-art bei Coding.",
    context_window: 200000,
    pricing_input: 3.00,
    pricing_output: 15.00,
    api_available: true,
    release_date: "2025-02-24",
    benchmarks: { mmlu: 88.5, humaneval: 92.5, math: 76.0, gpqa: 62.0, arena_elo: 1335 },
    pros: ["Hybrid-Reasoning: Schnell oder tiefgründig", "Bestes Coding-Modell", "Claude Code Agent", "Kontrollierbares Thinking-Budget"],
    cons: ["Teuer im Extended-Thinking-Modus", "Thinking Tokens kosten extra"],
    best_for: ["Coding", "Agentic Workflows", "Debugging", "Refactoring"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_new: true,
  },
  // NEU: Gemini 2.0 Flash (Feb 2025)
  {
    id: "gemini-2-0-flash",
    name: "Gemini 2.0 Flash",
    provider: "Google",
    type: "multimodal",
    category: ["llm", "multimodal", "vision", "fast"],
    description: "Schnelles multimodales Modell mit 1M Token Kontextfenster. Optimiert für Agent-Anwendungen.",
    context_window: 1000000,
    pricing_input: 0.10,
    pricing_output: 0.40,
    api_available: true,
    release_date: "2025-02-05",
    benchmarks: { mmlu: 84.5, humaneval: 87.0, math: 72.0, gpqa: 52.0, arena_elo: 1280 },
    pros: ["Riesiges 1M Kontextfenster", "Sehr günstig", "Native Tool-Nutzung", "Multimodal"],
    cons: ["Weniger präzise als Pro", "Inkonsistent bei komplexen Aufgaben"],
    best_for: ["Lange Dokumente", "Video-Analyse", "Agent-Apps", "Kostenbewusste Projekte"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_new: true,
  },
  // NEU: Gemini 2.0 Pro (Feb 2025)
  {
    id: "gemini-2-0-pro",
    name: "Gemini 2.0 Pro",
    provider: "Google",
    type: "multimodal",
    category: ["llm", "multimodal", "reasoning"],
    description: "Googles leistungsstärkstes Modell mit 2M Token Kontextfenster (experimentell).",
    context_window: 2000000,
    pricing_input: 1.25,
    pricing_output: 10.00,
    api_available: true,
    release_date: "2025-02-05",
    benchmarks: { mmlu: 87.8, humaneval: 90.2, math: 75.0, gpqa: 58.0, arena_elo: 1320 },
    pros: ["Größtes Kontextfenster (2M)", "Hervorragendes Reasoning", "Multimodal"],
    cons: ["Noch experimentell", "Höhere Latenz"],
    best_for: ["Riesige Dokumente", "Codebases", "Forschung", "Enterprise"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_new: true,
  },
  // DeepSeek V3 (aktualisiert)
  {
    id: "deepseek-v3",
    name: "DeepSeek V3",
    provider: "DeepSeek",
    type: "llm",
    category: ["llm", "coding", "open-source", "reasoning"],
    description: "Open-Source-Modell mit extrem günstigen Preisen. 128K Kontext, hervorragendes Reasoning.",
    context_window: 128000,
    pricing_input: 0.28,
    pricing_output: 0.42,
    api_available: true,
    release_date: "2024-12-26",
    benchmarks: { mmlu: 85.2, humaneval: 89.8, math: 74.0, gpqa: 55.0, arena_elo: 1278 },
    pros: ["Extrem günstig", "Open Source", "Hervorragendes Reasoning", "128K Kontext"],
    cons: ["Zensur bei sensiblen Themen", "Weniger bekannt"],
    best_for: ["Budget-Projekte", "Coding", "Reasoning", "API-Integration"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
  },
  // DeepSeek R1 (Reasoning)
  {
    id: "deepseek-r1",
    name: "DeepSeek R1",
    provider: "DeepSeek",
    type: "llm",
    category: ["llm", "reasoning", "open-source"],
    description: "Reasoning-Modell mit Chain-of-Thought. Konkurrenzfähig mit o1, aber viel günstiger.",
    context_window: 128000,
    pricing_input: 0.55,
    pricing_output: 2.19,
    api_available: true,
    release_date: "2025-01-20",
    benchmarks: { mmlu: 87.5, humaneval: 91.5, math: 91.2, gpqa: 65.0, arena_elo: 1295 },
    pros: ["Hervorragendes Reasoning", "Sichtbares Chain-of-Thought", "Sehr günstig", "Open Source"],
    cons: ["Nur Englisch/Chinesisch", "Zensur"],
    best_for: ["Mathematik", "Wissenschaft", "Logik", "Reasoning"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
  },
  // GPT-4o (aktualisiert)
  {
    id: "gpt-4o",
    name: "GPT-4o",
    provider: "OpenAI",
    type: "multimodal",
    category: ["llm", "multimodal", "vision", "audio"],
    description: "OpenAIs multimodales Flaggschiff. Text, Bild, Audio und Video in Echtzeit.",
    context_window: 128000,
    pricing_input: 2.50,
    pricing_output: 10.00,
    api_available: true,
    release_date: "2024-05-13",
    benchmarks: { mmlu: 87.2, humaneval: 90.1, math: 76.6, gpqa: 53.6, arena_elo: 1312 },
    pros: ["Multimodal", "Großes Ökosystem", "Zuverlässige API", "Echtzeit-Audio"],
    cons: ["Höherer Preis", "Weniger transparent"],
    best_for: ["Multimodale Apps", "Echtzeit-Anwendungen", "API-Integration"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
  },
  // Claude 3.5 Sonnet (Legacy, aber noch relevant)
  {
    id: "claude-3-5-sonnet",
    name: "Claude 3.5 Sonnet",
    provider: "Anthropic",
    type: "llm",
    category: ["llm", "coding", "reasoning"],
    description: "Ausgezeichnetes Preis-Leistungs-Verhältnis. Noch sehr beliebt für Coding.",
    context_window: 200000,
    pricing_input: 3.00,
    pricing_output: 15.00,
    api_available: true,
    release_date: "2024-06-20",
    benchmarks: { mmlu: 85.4, humaneval: 92.0, math: 71.1, gpqa: 59.4, arena_elo: 1301 },
    pros: ["Exzellentes Coding", "Großes Kontextfenster", "Natürliche Konversation"],
    cons: ["Kein Internet-Zugriff", "Kein Reasoning-Modus wie 3.7"],
    best_for: ["Coding", "Dokumentenanalyse", "Schreiben"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
  },
  // Grok 3 (xAI)
  {
    id: "grok-3",
    name: "Grok 3",
    provider: "xAI",
    type: "llm",
    category: ["llm", "real-time", "reasoning"],
    description: "xAIs neuestes Modell mit Echtzeit-X-Integration und Reasoning-Fähigkeiten.",
    context_window: 128000,
    pricing_input: 3.00,
    pricing_output: 15.00,
    api_available: true,
    release_date: "2025-02-17",
    benchmarks: { mmlu: 86.5, humaneval: 89.0, math: 78.0, gpqa: 58.0, arena_elo: 1310 },
    pros: ["Echtzeit-X-Integration", "Weniger zensiert", "Reasoning-Modus"],
    cons: ["Nur über X/Twitter", "Weniger reif"],
    best_for: ["News-Analyse", "Social Media", "Echtzeit-Informationen"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_new: true,
  },
  // GPT-4.5 (OpenAI - Feb 27, 2025)
  {
    id: "gpt-4-5",
    name: "GPT-4.5",
    provider: "OpenAI",
    type: "llm",
    category: ["llm", "multimodal", "reasoning"],
    description: "OpenAIs größtes und bestes Chat-Modell. Erweitertes unsupervised learning für natürlichere Interaktionen.",
    context_window: 128000,
    pricing_input: 75.00,
    pricing_output: 150.00,
    api_available: true,
    release_date: "2025-02-27",
    benchmarks: { mmlu: 89.0, humaneval: 91.5, math: 78.0, gpqa: 62.0, arena_elo: 1340 },
    pros: ["Höchste 'EQ' aller GPT-Modelle", "Weniger Halluzinationen", "Natürlichere Konversation", "Starke Kreativität"],
    cons: ["Extrem teuer", "Kein Reasoning wie o1", "Nur für Pro/Plus User"],
    best_for: ["Writing", "Coaching", "Brainstorming", "Kreative Aufgaben"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_new: true,
  },
  // Qwen 2.5 Max (Alibaba)
  {
    id: "qwen-2-5-max",
    name: "Qwen 2.5 Max",
    provider: "Alibaba",
    type: "llm",
    category: ["llm", "coding", "open-source"],
    description: "Alibabas stärkstes Modell. Top 10 auf LMSYS Arena.",
    context_window: 128000,
    pricing_input: 1.60,
    pricing_output: 6.40,
    api_available: true,
    release_date: "2025-01-28",
    benchmarks: { mmlu: 86.0, humaneval: 88.5, math: 73.0, gpqa: 54.0, arena_elo: 1332 },
    pros: ["Top-Performance", "Gute Chinesisch-Übersetzung", "Open-Source-Varianten"],
    cons: ["Weniger bekannt außerhalb Chinas", "Begrenzte Dokumentation"],
    best_for: ["Coding", "Asiatische Märkte", "Mehrsprachige Apps"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
    is_new: true,
  },
  // Llama 3.3 70B
  {
    id: "llama-3-3-70b",
    name: "Llama 3.3 70B",
    provider: "Meta",
    type: "llm",
    category: ["llm", "open-source"],
    description: "Effizientes Open-Source-Modell. Fast gleiche Performance wie 405B.",
    context_window: 128000,
    pricing_input: 0.12,
    pricing_output: 0.30,
    api_available: true,
    release_date: "2024-12-06",
    benchmarks: { mmlu: 82.1, humaneval: 86.5, math: 70.0, gpqa: 48.0, arena_elo: 1250 },
    pros: ["Kostenlos", "Open Source", "Effizient", "Großes Ökosystem"],
    cons: ["Weniger leistungsfähig als Top-Modelle", "Selbst-Hosting erforderlich"],
    best_for: ["Selbst-Hosting", "Datenschutz", "Forschung", "Budget"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
  },
  // GPT-4o Mini
  {
    id: "gpt-4o-mini",
    name: "GPT-4o Mini",
    provider: "OpenAI",
    type: "multimodal",
    category: ["llm", "budget", "multimodal"],
    description: "Günstige Alternative zu GPT-4o. Für einfache Aufgaben ideal.",
    context_window: 128000,
    pricing_input: 0.15,
    pricing_output: 0.60,
    api_available: true,
    release_date: "2024-07-18",
    benchmarks: { mmlu: 78.9, humaneval: 81.2, math: 68.0, gpqa: 42.0, arena_elo: 1220 },
    pros: ["Sehr günstig", "Schnell", "Multimodal"],
    cons: ["Weniger leistungsfähig", "Eingeschränkte Fähigkeiten"],
    best_for: ["Einfache Aufgaben", "Prototyping", "Low-Budget"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
  },
  // Mistral Large 2
  {
    id: "mistral-large-2",
    name: "Mistral Large 2",
    provider: "Mistral AI",
    type: "llm",
    category: ["llm", "european"],
    description: "Europäisches Modell mit starken Multilingual-Fähigkeiten.",
    context_window: 128000,
    pricing_input: 2.00,
    pricing_output: 6.00,
    api_available: true,
    release_date: "2024-07-24",
    benchmarks: { mmlu: 81.8, humaneval: 85.2, math: 68.0, gpqa: 48.0, arena_elo: 1245 },
    pros: ["Europäisch", "Multilingual", "Gute Preisgestaltung"],
    cons: ["Weniger bekannt", "Kleinere Community"],
    best_for: ["Europäische Unternehmen", "Multilingual", "GDPR"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
  },
  // Bildgenerierung
  {
    id: "midjourney-v6",
    name: "Midjourney v6",
    provider: "Midjourney",
    type: "image",
    category: ["image", "art"],
    description: "Führendes KI-Bildgenerierungsmodell für künstlerische Bilder.",
    context_window: 0,
    pricing_input: 8.00,
    pricing_output: 0,
    api_available: false,
    release_date: "2023-12-21",
    benchmarks: { aesthetics: 95, prompt_adherence: 92 },
    pros: ["Beste Bildqualität", "Künstlerischer Stil", "Aktive Community"],
    cons: ["Keine API", "Discord erforderlich", "Teuer"],
    best_for: ["Kunst", "Marketing", "Konzept-Design"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
  },
  {
    id: "dall-e-3",
    name: "DALL-E 3",
    provider: "OpenAI",
    type: "image",
    category: ["image", "api"],
    description: "OpenAIs Bildgenerierungsmodell mit exzellenter Prompt-Einhaltung.",
    context_window: 0,
    pricing_input: 4.00,
    pricing_output: 0,
    api_available: true,
    release_date: "2023-10-01",
    benchmarks: { aesthetics: 85, prompt_adherence: 95 },
    pros: ["API verfügbar", "Gute Prompt-Einhaltung", "ChatGPT-Integration"],
    cons: ["Weniger künstlerisch", "Eingeschränkte Kontrolle"],
    best_for: ["API-Integration", "Content-Erstellung", "ChatGPT-User"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
  },
  // Video
  {
    id: "sora",
    name: "Sora",
    provider: "OpenAI",
    type: "video",
    category: ["video", "multimodal"],
    description: "KI-Modell für die Generierung realistischer Videos aus Text.",
    context_window: 0,
    pricing_input: 0,
    pricing_output: 0,
    api_available: false,
    release_date: "2024-12-09",
    benchmarks: { quality: 90, coherence: 88 },
    pros: ["Realistische Videos", "Lange Sequenzen", "Physik-Verständnis"],
    cons: ["Nur für ausgewählte User", "Hohe Kosten"],
    best_for: ["Video-Produktion", "Storyboarding", "Marketing"],
    video_url: "https://www.youtube.com/embed/-AJoByRGkgU",
  },
];

// Top 5 Modelle für Februar 2025
export const topModels = [
  {
    rank: 1,
    name: "GPT-4.5",
    provider: "OpenAI",
    arena_elo: 1340,
    mmlu: 89.0,
    context: "128K",
    price_input: 75.00,
    price_output: 150.00,
    highlight: "OpenAIs größtes Chat-Modell",
  },
  {
    rank: 2,
    name: "Claude 3.7 Sonnet",
    provider: "Anthropic",
    arena_elo: 1335,
    mmlu: 88.5,
    context: "200K",
    price_input: 3.00,
    price_output: 15.00,
    highlight: "Erstes Hybrid-Reasoning-Modell",
  },
  {
    rank: 3,
    name: "Qwen 2.5 Max",
    provider: "Alibaba",
    arena_elo: 1332,
    mmlu: 86.0,
    context: "128K",
    price_input: 1.60,
    price_output: 6.40,
    highlight: "Top 10 auf LMSYS Arena",
  },
  {
    rank: 4,
    name: "Gemini 2.0 Pro",
    provider: "Google",
    arena_elo: 1320,
    mmlu: 87.8,
    context: "2M",
    price_input: 1.25,
    price_output: 10.00,
    highlight: "Größtes Kontextfenster (2M)",
  },
  {
    rank: 5,
    name: "GPT-4o",
    provider: "OpenAI",
    arena_elo: 1312,
    mmlu: 87.2,
    context: "128K",
    price_input: 2.50,
    price_output: 10.00,
    highlight: "Beste Multimodal-Fähigkeiten",
  },
];

// Neue Modelle diese Woche
export const newThisWeek = [
  {
    name: "GPT-4.5",
    provider: "OpenAI",
    release_date: "2025-02-27",
    description: "OpenAIs größtes Chat-Modell mit höherer EQ und weniger Halluzinationen",
    category: "LLM / Multimodal",
  },
  {
    name: "Claude 3.7 Sonnet",
    provider: "Anthropic",
    release_date: "2025-02-24",
    description: "Erstes Hybrid-Reasoning-Modell mit Claude Code Agent",
    category: "LLM / Coding",
  },
  {
    name: "Grok 3",
    provider: "xAI",
    release_date: "2025-02-17",
    description: "xAIs neuestes Modell mit Reasoning und Echtzeit-Daten",
    category: "LLM / Real-time",
  },
  {
    name: "Gemini 2.0 Flash & Pro",
    provider: "Google",
    release_date: "2025-02-05",
    description: "Neue Generation mit 1M/2M Kontextfenster",
    category: "Multimodal",
  },
];

// Preisvergleich
export const priceComparison = [
  { model: "Gemini 2.0 Flash", provider: "Google", input: 0.10, output: 0.40, context: "1M" },
  { model: "DeepSeek V3", provider: "DeepSeek", input: 0.28, output: 0.42, context: "128K" },
  { model: "Llama 3.3 70B", provider: "Meta", input: 0.12, output: 0.30, context: "128K" },
  { model: "GPT-4o Mini", provider: "OpenAI", input: 0.15, output: 0.60, context: "128K" },
  { model: "Claude 3.5 Sonnet", provider: "Anthropic", input: 3.00, output: 15.00, context: "200K" },
  { model: "Claude 3.7 Sonnet", provider: "Anthropic", input: 3.00, output: 15.00, context: "200K" },
  { model: "GPT-4o", provider: "OpenAI", input: 2.50, output: 10.00, context: "128K" },
  { model: "Gemini 2.0 Pro", provider: "Google", input: 1.25, output: 10.00, context: "2M" },
  { model: "GPT-4.5", provider: "OpenAI", input: 75.00, output: 150.00, context: "128K" },
];
